# Generated by Django 5.2 on 2025-05-03 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='referral',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='be41b63a82da', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='vip_level',
            field=models.CharField(default='VIP0', max_length=4),
        ),
    ]
