# Generated by Django 5.2 on 2025-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='has_recharged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_income_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='5bcf8aa6d02c', max_length=12, unique=True),
        ),
    ]
