# Generated by Django 5.2 on 2025-05-09 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wallet_has_recharged_wallet_last_income_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='airtel_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from Airtel Money or M-Pesa (e.g., QJ1234567890)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='ac2ed0694287', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number for recharge", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
