# Generated by Django 5.2 on 2025-05-10 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_airtel_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='transaction',
            field=models.OneToOneField(blank=True, limit_choices_to={'status': 'PENDING', 'transaction_type': 'RECHARGE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='ce4f41fa162a', max_length=12, unique=True),
        ),
    ]
