# Generated by Django 5.2 on 2025-05-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_recharge_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='transaction',
            field=models.OneToOneField(blank=True, limit_choices_to={'transaction_type': 'RECHARGE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='e84017ca4be0', max_length=12, unique=True),
        ),
    ]
