# Generated by Django 5.2 on 2025-05-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recharge_username_alter_recharge_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='804e18c2d177', max_length=12, unique=True),
        ),
    ]
