# Generated by Django 5.2 on 2025-05-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_recharge_phone_number_alter_recharge_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='78df8bb8fa44', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction'),
        ),
    ]
