# Generated by Django 5.2 on 2025-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_withdrawal_phone_number_alter_referral_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='e7aac055d60a', max_length=12, unique=True),
        ),
    ]
