# Generated by Django 5.2 on 2025-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaction_fee_alter_referral_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='b56a50e50f0f', max_length=12, unique=True),
        ),
    ]
