# Generated by Django 5.2 on 2025-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_cost_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='af02f1b56927', max_length=12, unique=True),
        ),
    ]
