# Generated by Django 5.2 on 2025-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='5017f11130ea', max_length=12, unique=True),
        ),
    ]
