# Generated by Django 5.2 on 2025-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='6b6cbd56d19d', max_length=12, unique=True),
        ),
    ]
