# Generated by Django 5.2 on 2025-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='53b79eb7b252', max_length=12, unique=True),
        ),
    ]
